### ISSUE TITLE
FR7. Create New Event

### ISSUE THREAD

**Issue by Cadek2002** [WSU-4110/Giftly#36]
|FR7. Create New Event|
|---|
|**Goal**: Allows users to create an event with templates and other customization tools.
**Stakeholders:** User|
| **Description:** In the process of creating an event, user will have choices of templates, modify it with settings, and generate/display an invite link.|
| **Origin:** Functionality Diagram Made for Initial Presentation|
| **Version:** 1.1  |  
|**Date:** 1/24/2023  
|  **Priority:** 1 |

**Comment by hannab8** [comment]
Will need to add popup screens for invite codes and adding other users.
